export * from './header/header.component';
export * from './home/home.component';
export * from './footer/footer.component';
export * from './product/product.component';
export * from './product-detail/product-detail.component';
export * from './product-partial/product-partial.component';
export * from './product-comment/product-comment.component';
//export * from './
//export * from './
//export * from './